# Generated by Django 4.2 on 2024-11-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemabiggu', '0003_actor_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=75),
        ),
    ]
