# Generated by Django 4.2.16 on 2024-11-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemabiggu', '0004_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
