# Generated by Django 4.2.16 on 2024-12-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemabiggu', '0006_genre_alter_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('capacity', models.IntegerField()),
                ('imax', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
