# Generated by Django 4.2 on 2024-10-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=80)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('avaliable', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
